### ISSUE TITLE
build.rs is too platform specific

### ISSUE THREAD

**Issue by mtmiller** [ctaggart/octh#10]
I can build the project by deleting the `--target=...` and changing the `-I/path/to/my/octave` options. What options or environment variables are available to cargo or bindgen to make this file less platform specific so anyone can build for their system?

**Comment by ctaggart** [comment]
@mtmiller Looking at the [stylo example](https://github.com/servo/servo/blob/master/components/style/build_gecko.rs#L143-L162), it looks like we can do something like:
``` rust
if cfg!(target_os = "windows") {

} else if cfg!(target_os = "macos") {

}
```
And there is more documentation at http://rustbyexample.com/attribute/cfg.html. I haven't done a ton of Rust coding either. Please do enhance it to work on your computer. Accepting PRs. :-)

**Comment by mtmiller** [comment]
That's not really what I'm reporting though. There is not one hardcoded location for Octave include files. If you and I are on the exact same distro, and my Octave header files are in /usr/local/octave/include and yours are in /opt/octave4.2/include, there must be a way to work that without every user having to edit this file. I would expect `CPPFLAGS=-I/opt/octave/include/octave-4.2.1/octave cargo build` to work, but it seems to be ignored. Maybe bindgen offers no way to do this.

**Comment by ctaggart** [comment]
@mtmiller, are you reporting that Octave header files may be installed in different locations? How do you recommend we look for them? How about an environment variable like this:
https://github.com/servo/servo/blob/master/components/style/build_gecko.rs#L49

**Comment by ctaggart** [comment]
#22 shows where to look for the headers on Linux.

**Comment by ctaggart** [comment]
Well, that's unfortunate. It looks like committing the generated file is not a good idea. The binding end up different between Windows and Linux as you can see here with 5.1.0:

![image](https://user-images.githubusercontent.com/80104/61183016-aa98c080-a676-11e9-9112-dc051fe05ceb.png)

**Comment by ctaggart** [comment]
I added a switch statement for different targets in #32.

**Comment by ctaggart** [comment]
Probably should support environment variables for the various paths. We can search for the existence of files in well known locations if not set.
