### ISSUE TITLE
unable to build against Octave dev (4.3.0+)

### ISSUE THREAD

**Issue by mtmiller** [ctaggart/octh#26]
When trying to build with Octave's development branch, compilation fails with the following

    error[E0432]: unresolved import `self::super::super::u32`
     --> src/lib.rs:5:3236
      |
    5 | ... huge wall of text snipped
      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `u32` in the root
    
    error[E0412]: cannot find type `T` in this scope
        --> src/lib.rs:2225:168
         |
    2225 | } # [ repr ( C ) ] # [ derive ( Debug , Copy , Clone ) ] pub struct tree_identifier { _unused : [ u8 ; 0 ] } } pub type octave_refcount = root :: octave :: refcount < T > ; 
         |                                                                                                                                                                        ^ not found in this scope
    
    error: aborting due to previous error(s)
    
    error: Could not compile `octh`.

The only difference is the paths given as `-I` options to bindgen in build.rs.

The first error looks like it's buried somewhere in the definition of `std::basic_string`. The second error comes from a line of C++ that looks like this

    template <typename T>
    using octave_refcount OCTAVE_DEPRECATED (4.4, "use 'octave::refcount' instead") = octave::refcount<T>;

**Comment by mtmiller** [comment]
https://github.com/rust-lang-nursery/rust-bindgen/issues/931

**Comment by mtmiller** [comment]
First error looks like #14, how did you resolve these errors before?

Second part is a known bindgen issue on valid C++11 syntax. AFAICT could be worked around by `ifdef`ing out the offending code, which is only there for a deprecation warning.

**Comment by ctaggart** [comment]
I think the best way to verify that this is the same bug is the run creduce on it overnight. It will produce the exact test case that we can hand off to them. I've done this for other bindgen issues. I've committed a couple of bindgen-bug*.sh scripts already to this repo.

**Comment by ctaggart** [comment]
I'm currently targeting Octave 5.1.0 as built by brew on my mac https://formulae.brew.sh/formula/octave. #15 was finally resolved. #36 is the latest error. I'm currently am running `creduce` for it and hoping that the perl isn't stuck in a loop at 84%.
